### ISSUE TITLE
No sites after Caller run

### ISSUE THREAD

**Issue by cnobles** [BushmanLab/simIntSiteReads#2]
After manually fixing the .tsv's, simData was processed through Caller. No data was returned. All runs were conducted with default settings.

The only files is the GTSP****-1 folder were: keys.RData, primerIDData.RData, and trimStatus.RData.

**Comment by yhwu** [comment]
see caller bug

**Comment by yhwu** [comment]
problem in trimming reads

**Comment by yhwu** [comment]
fixed
