### ISSUE TITLE
Data frame of sites can be passed directly to get_sequence_downstream

### ISSUE THREAD

**Issue by kylebittinger** [BushmanLab/simIntSiteReads#3]
Data frame is split by column when the function is called:
https://github.com/BushmanLab/simIntSiteReads/blob/master/simIntSiteReads.R#L127

Data frame is re-created here: 
https://github.com/BushmanLab/simIntSiteReads/blob/master/simIntSiteReads_func.R#L87

This step can be eliminated by simply passing the data frame to the function

**Comment by yhwu** [comment]
easier to debug and expand
